### ISSUE TITLE
[Feature Request] Support PSR-6 Caching

### ISSUE THREAD

**Issue by core23** [heiseonline/shariff-backend-php#105]
It would be a good idea to implement the PSR caching interface, this would remove the hard dependency to zend and allows you to change the caching library.

http://www.php-fig.org/psr/psr-6/

**Comment by liayn** [comment]
We already have an intermediate step by having the CacheInterface I introduced back in the days. I need that in our TYPO3 integration, where I remove the zend dependencies completely and stick the TYPO3 caching framework into place. That works like a charme as the users can simply use the "Clear caches" button of the TYPO3 backend.

**Comment by core23** [comment]
The problem is the composer file, where the zend dependency is loaded, even if you don't need it:
https://github.com/heiseonline/shariff-backend-php/blob/master/composer.json#L23

**Comment by liayn** [comment]
> where I remove the zend dependencies completely

I adjust the composer.json in my TYPO3 branch to get rid of the zend stuff.

**Comment by liayn** [comment]
I of course appreciate following as many standards as possible.

**Comment by liayn** [comment]
Strange enough zendcache is listed as psr/cache dependent, even though it is not required... weird
https://packagist.org/packages/psr/cache/dependents?page=10

**Comment by liayn** [comment]
My last comment explains that way: zendcache requires psr/cache in branch `dev-develop` only.
