### ISSUE TITLE
Default installation leaks shariff.json with Facebook App secret

### ISSUE THREAD

**Issue by cmaas** [heiseonline/shariff-backend-php#106]
If you follow the installation instructions, `shariff.json` will be accessible by entering the URL in the browser, e. g. `http://example.com/shariff-backend-php/shariff.json`. This exposes the Facebook App secret if one was entered.

Fix: Bring awareness to this issue and give clear instructions on how to make shariff.json not readable.

**Comment by liayn** [comment]
next release will not contain a Json anymore. See pending PR. I migrated that to a plain PHP array.

**Comment by liayn** [comment]
Oh PR #104 just got merged. So, done.

**Comment by compeak** [comment]
Fixed in [6.0.0](https://github.com/heiseonline/shariff-backend-php/releases/tag/6.0.0). Please feel free to reopen this issue if you have further questions.
