### ISSUE TITLE
New patch release after guzzle security fix please

### ISSUE THREAD

**Issue by cedricziel** [heiseonline/shariff-backend-php#107]
Could you please release a new patch version after a16876d423726368c005e7513ebbed2da77608b5 ?

It's unnecessarily hard to cope with, when shariff is a third level dependency.

Thank you! :)

**Comment by compeak** [comment]
I just released [5.2.4](https://github.com/heiseonline/shariff-backend-php/releases/tag/5.2.4) based on 145f8a6864d086412e57be2d64cb6db28ffb509c. Please be aware that this release is marked as **not supported**.

**Comment by cedricziel** [comment]
Thank you!
