### ISSUE TITLE
Build process and repository structure

### ISSUE THREAD

**Issue by devimplode** [heiseonline/shariff-backend-php#11]
Hi,
wie ihr ja wisst habe ich in der jüngsten Zeit exzessiv mit dem Projekt hier rumgespielt... und das einzige das am php-Backend nervt: der Build-Prozess 

Nun, aktuell haben wir das build-Verzeichnis im repo.
Geile Sache erstmal - keiner will composer einrichten und *all the dependencies* fetchen

###### First World Problems
- wir vergessen `./build.sh` vor dem commit - quasi immer?
- wir vergessen `build/` zu testen - könnte Travis-CI übernehmen (btw: Ich glaube das würde aktuell failen)
- wir vergessen regelmäßig die dependencies zu updaten - was dazu führt das wir uns gegenseitig neue/alte Versionen in `build/` überschreiben
- diffs, ganz speziell nach composer updates, sind verdammt schwer zu lesen

###### Vorschlag
Im master-Branch den reinen Code lassen und `build/` entfernen.
Einen separaten build-Branch erstellen in dem `vendor/` geupdated wird - ganz groß in der README.md darauf verweißen.

Eventuell per [pre-commit Script](http://git-scm.com/book/de/v1/Git-individuell-einrichten-Git-Hooks) tests und build erzwingen?

Was haltet Ihr davon?

**Comment by pmb0** [comment]
Mit dem Build-Prozess bin ich auch ein bisschen unzufrieden. Eigentlich moechte ich den Build gar nicht mit committen; das ist ein Kompromiss fuer User, die kein composer verwenden und einfach sofort eine Zip-Datei entpacken und loslegen wollen.

Ausserdem finde ich, dass gar nicht fuer jeden Commit ein Build erzeugt werden sollte, wohl aber fuer jedes Release. D.h., etwas wie `npm version {major|minor|patch}` waere praktisch, das einerseits einen git-Tag und andererseits ein Release erstellt. 

Am besten ware es vermutlich, `build/` komplett aus dem Repo zu entfernen und mit der [Releases-API](https://developer.github.com/v3/repos/releases/#create-a-release) einen Release zu erstellen, welches *nur* den Inhalt von `build/` enthaelt. Oder?

**Comment by devimplode** [comment]
Ich hab echt keine Ahnung von dem ganzen kram... aber... Das hört sich gut an!

Bin definitiv für frischen Build bei jedem getesteten und getagten Release.

Ich für meinen Teil würde erstmal `build/` (den ich für mein eigenes deployment benötige) erstmal in meine `.gitignore` schreiben - nur kann man das dann nicht mehr commiten wenn es benötigt wird - also werde ich `build/` wohl in ruhe lassen und ignorieren und `staging/` oder so für meinen local build nehmen.
Andere Option wäre wir lassen den source in einem develop-Branch und im master sind nur die builds fürs direkte runterladen.

Was gibt es für PHP eigentlich an Grunt/Gulp-Ersatz?

**Comment by uwej711** [comment]
Man kann mit travis Dateien zu einem Release dazu packen. Nach etwas Suchen habe ich das z.B. bei Guzzle gefunden:

https://github.com/guzzle/guzzle/blob/master/.travis.yml  Einträge before_deploy und deploy. Unkalr ist mir nur noch, wie man den api_key erzeugt.

Das Zip wird dort mir https://github.com/mtdowling/Burgomaster gebaut, dazu Einträge im Makefile (https://github.com/guzzle/guzzle/blob/master/Makefile, ganz unten, package) und das Skript packager.php (https://github.com/guzzle/guzzle/blob/master/build/packager.php)

**Comment by core23** [comment]
Gibt es hier schon einen neuen Stand, wann und ob das ``build`` Verzeichnis entfernt wird?

Man könnte sonst vielleicht auch weiteres Repo als Readonly erstellen wo nur der reine Quellcode abgelegt wird. Symfony macht es zum Teil ähnlich (z.B. https://github.com/symfony/Form als Teil von https://github.com/symfony/symfony/tree/2.8/src/Symfony/Component/Form)

**Comment by frankenpfalzer** [comment]
@devimplode: Ich kenne [Phing](https://www.phing.info/) als Buildsystem für PHP. Von der Syntax her, ist es an Ant aus der Java-Welt angelehnt. Ich hab mal spaßenshalber den Versuch unternommen dieses Projekt hier mit phing zu bauen(s. https://github.com/frankenpfalzer/shariff-backend-php/commit/6ecf292ed9ced315bf67eb0aba51b34ad505fb21)

**Comment by davidgorges** [comment]
Das Build-Verzeichnis im Repository ist wirklich unnötig (und verwirrend). 

Warum nicht Releases erstellen und als ZIP-Download anbieten (für User, die Composer nicht nutzen)?

**Comment by compeak** [comment]
> Man kann mit travis Dateien zu einem Release dazu packen.

Das ist, was wir machen werden. Ich habe das in [travis-build](https://github.com/heiseonline/shariff-backend-php/tree/travis-build) umgesetzt und gucke jetzt noch, wie ich es testen kann.

**Comment by uwej711** [comment]
https://travis-ci.org/heiseonline/shariff-backend-php/jobs/94164485#L376

Evtl. einen Tag auf dem Branch setzen?

**Comment by compeak** [comment]
> Evtl. einen Tag auf dem Branch setzen?

Das hat funktioniert.

Ein Problem ist jetzt, [dass Travis wohl nicht immer die composer-dist-Pakete bekommt](https://travis-ci.org/heiseonline/shariff-backend-php/jobs/94343676#L174). Es wird dann auf Quelltext-Pakete ausgewichen, in denen die .git-Verzeichnisse noch vorhanden sind. Deshalb ist [der aktuelle Release-Build](https://github.com/heiseonline/shariff-backend-php/releases/tag/3.0.0) 64 MB (!!!) gross.

**Comment by compeak** [comment]
Ich habe das zip und das tar.gz von Hand aktualisiert. Allem Anschein nach benutzt Travis nie die dist-Pakete. Mit `--prefer-dist` gibt es [diese](https://travis-ci.org/heiseonline/shariff-backend-php/jobs/94343679#L149) Fehlermeldungen.

**Comment by compeak** [comment]
Sieht so aus, als waere das ein Problem mit dem Rate-Limit der GitHub-API.

**Comment by compeak** [comment]
[Diese Anleitung](http://blog.wyrihaximus.net/2015/09/github-auth-token-on-travis/) funktioniert. Composer laedt jetzt die dist-Pakete statt der Repositories.
