### ISSUE TITLE
Probleme mit shariff als subdomain

### ISSUE THREAD

**Issue by frankthies** [heiseonline/shariff-backend-php#111]
Hallo,

da ich mehrere Websites betreibe und shariff nur einmal einrichten möchte - um Updates zu vereinfachen - habe ich shariff in einer subdomain einer meiner Websites installiert (shariff.domain.de) und dort alle genutzten Domains eingetragen.

Solange ich shariff im Unterordner /shariff/ eingerichtet hatte, klappte die Anzeige auch einwandfrei. 

Code: data-backend-url="/shariff/"

Beim Aufruf von shariff via Subdomain werden aber bei Facebook, Google+ etc. keine Counter angezeigt. Wenn ich einen Testlink direkt aufrufe bekomme ich aber ein Array mit den entsprechenden Werten angezeigt.

Code: data-backend-url="http://shariff.domain.de/"

Hat jemand eine Idee, woran das liegen könnte?

Danke im Voraus / VG

Frank-Andre

**Comment by liayn** [comment]
Hallo!

Hast du die `domains` option richtig konfiguriert, sodass alle anderen domains erlaubt sind?

Ansonsten bitte noch um genauere Info, wann wo was wie liegt.
Liegt der Unterordner auch auf der shariff-subdomain oder jeweils auf den anderen domains?
Welchen Test-Link verwendest du?

**Comment by frankthies** [comment]
Hallo liayn,

Danke dass Du versuchst mir zu helfen!!!! Ich versuche es mal besser zu erläutern :)

Ja, die Variable `domains` habe ich richtig konfiguriert.

Bisher habe ich die shariff-Dateien bei meinen Websites in einem Unterordner liegen. Bsp: cheatscorner.de 
Dort werden die share counts auch korrekt angezeigt und der Testlink zeigt das entsprechende Array an:

http://www.cheatscorner.de/shariff/?url=http%3A%2F%2Fwww.cheatscorner.de

Damit ich nicht jedesmal bei Updates von shariff alle Seiten updaten muss, habe ich shariff als Subdomain auf einer meiner Seiten angelegt. Und wenn ich dort den Testlink aufrufe, erscheint ebenfalls ein Array und zeigt damit, dass shariff grundsätzlich funktioniert.

http://shariff.f-thies.de/?url=http%3A%2F%2Fwww.cheatscorner.de

Wenn ich nun aber in der Website den Code `data-backend-url="/shariff/"` ersetze mit `data-backend-url="http://shariff.f-thies.de/"` werden die share counts nicht mehr angezeigt. 

Und ich finde einfach nicht heraus, woran das liegen könnte. Hast Du eine Idee?

Danke / VG

Frank-Andre

**Comment by liayn** [comment]
Kann es sein, dass dein Problem schon gelöst ist?
Wenn ich auf http://www.cheatscorner.de schaue, sehe ich bereits die counter, diee auch der Testlink liefert.

**Comment by frankthies** [comment]
Leider nein. Dort läuft noch die shariff-Version die im Unterordner installiert ist. Sobald ich wie geschrieben auf shariff.f-thies.de umstelle, werden sie share counts nicht mehr angezeigt. Und das obwohl der Testlink die korrekten Werte liefert.                                                                                                                                                                                  ‎                              Von: Markus KleinGesendet: Montag, 26. September 2016 01:15An: heiseonline/shariff-backend-phpAntwort an: heiseonline/shariff-backend-phpCc: frankthies; AuthorBetreff: Re: [heiseonline/shariff-backend-php] Probleme mit shariff als subdomain (#111)Kann es sein, dass dein Problem schon gelöst ist?
Wenn ich auf http://www.cheatscorner.de schaue, sehe ich bereits die counter, diee auch der Testlink liefert.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/heiseonline/shariff-backend-php","title":"heiseonline/shariff-backend-php","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/heiseonline/shariff-backend-php"}},"updates":{"snippets":[{"icon":"PERSON","message":"@liayn in #111: Kann es sein, dass dein Problem schon gelöst ist?\r\nWenn ich auf http://www.cheatscorner.de schaue, sehe ich bereits die counter, diee auch der Testlink liefert."}],"action":{"name":"View Issue","url":"https://github.com/heiseonline/shariff-backend-php/issues/111#issuecomment-249452874"}}}

**Comment by compeak** [comment]
@frankthies Du hast in Deiner Antwort einen API-Key geleaked.

Ist das evtl. ein [Cross-Origin](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)-Problem?

**Comment by liayn** [comment]
@frankthies Um noch genauer zu sein: Die shariff.json Datei sollte keinesfalls öffentlich zugreifbar sein!
(Um diesen potentiellen Fehler zu vermeiden, gibt es in der aktuellen Version diese Datei schlicht nicht mehr.)

**Comment by frankthies** [comment]
Danke für die beiden Hinweise. Was empfiehlst Du um die json-Datei vor öffentlichen Zugriffen zu schützen?

Das mit dem Cross-Origin könnte natürlich die Ursache sein, werde mal meinen System-Admin um Unterstützung bitten-

**Comment by liayn** [comment]
Entweder die config direkt in die `index.php` schreiben (siehe aktuelle Version) oder mittels webserver config den Zugriff auf die .json blockieren. (.htaccess bei apache)

**Comment by frankthies** [comment]
Habe mal versucht mich mit dem Thema Cross-Origin und so zu beschäftigen. Finde aber keine Lösung :( 

Gibt es denn dafür überhaupt eine Lösung?

**Comment by compeak** [comment]
> Gibt es denn dafür überhaupt eine Lösung?

Es würde mich wundern, wenn es keine gäbe.

Wenn du `shariff.f-thies.de` in eine Seite einbindest, die unter einer anderen Domain abrufbar ist, muss `shariff.f-thies.de` CORS-header senden, die dies erlauben.

`shariff.f-thies.de` müsste in etwa diesen header setzten:

```
Access-Control-Allow-Origin: http://www.cheatscorner.de
# optional zusätzlich auch
Access-Control-Allow-Methods: GET
```
Falls du die Sicherheitsfunktion von CORS nicht haben willst (solltest du aber eigentlich wollen), kannst du auch
```
Access-Control-Allow-Origin: *
```
senden. Das gibt dann Alles frei.

[Hier](http://enable-cors.org/server.html) steht noch, wie man CORS anschaltet.

**Comment by compeak** [comment]
Da es keine Rückmeldung gab, schließe ich das Ticket. Bitte bei Bedarf wieder öffnen.
