### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by core23** [heiseonline/shariff-backend-php#115]
Please tag a new release to get this https://github.com/heiseonline/shariff-backend-php/commit/b16fbc27d276782543c1d47673afb588cb4c8808

**Comment by core23** [comment]
Ping @liayn

**Comment by liayn** [comment]
@core23 how can I be of help?

**Comment by core23** [comment]
Sorry, picked the wrong guy  :sweat_smile:

@compeak Can you create a new tag please

**Comment by compeak** [comment]
I just published 6.0.1.
