### ISSUE TITLE
Google-Counter immer 0?

### ISSUE THREAD

**Issue by SPQRInc** [heiseonline/shariff-backend-php#131]
Hallo zusammen,

der Google-Share-Counter steht bei mir immer auf 0, obwohl der Artikel (z.B. hier: https://spqr.wtf/blog/2018/01/19/migrate-from-bower-to-npm-webpack) geteilt wurde.

Die Konfiguration sollte hier eigentlich passen: https://github.com/SPQRInc/pagekit-shariff/blob/master/src/Controller/ShariffApiController.php#L64-L85

**Comment by richard67** [comment]
@SPQRInc Soweit ich weiß beinhaltet der Original-Share-Button von Google seit etwa Mitte 2017 keinen Share-Count mehr, damit er schneller geladen wird. Es gibt dazu ein Bulletin von Google. Ich werde den Link hier später posten. Soweit ich Google verstehe heißt das auch, dass die Zähler nicht mehr abgefragt werden können mit dem vom Shariff-Backend verwendeten Key. Ob ich s mit einem eigenen App-Key funktionieren würde weiß ich nicht. Aber wie ich auf zahlreichen Webseiten sehen konnte sind überall, also auch bei Heise.de alle Google-Zähler Null. Du machst also erstmal nichts falsch.

**Comment by richard67** [comment]
https://plus.google.com/110610523830483756510/posts/Z1FfzduveUo

**Comment by richard67** [comment]
And https://stackoverflow.com/questions/45157191/google-share-counts-are-not-showing

**Comment by richard67** [comment]
I think I will later make a pull request to remove the google+ service from Shariff PHP backend.

**Comment by richard67** [comment]
@compeak Could you check those links I provided and decide if the google service should be removed from backend? If so, I can make a pull request.

**Comment by compeak** [comment]
@richard67 I believe the G+ service should be removed since it does not work as expected anymore.

**Comment by richard67** [comment]
Ok, I will make a pull request later today or on weekend.

**Comment by richard67** [comment]
Pull request is #132

**Comment by richard67** [comment]
As the PR is merged, this issue can be closed.
