### ISSUE TITLE
Feature Request: Tracking-Suffix an URL

### ISSUE THREAD

**Issue by dertimm** [heiseonline/shariff-backend-php#133]
Hallo zusammen,

ich finde shariff eine super Entwicklung und freue mich seit dem Einsatz in der Wordpress-Installation immer wieder über die datenschutzkonforme Lösung.
Im Rahmen der Webseitenanalyse wäre es noch schön, die Effektivtät der Shares zu messen. Gibt es eine Möglichkeit, an die jeweiligen URLs noch ein Suffix hängen zu können? Damit könnten die Shares insgesamt schonmal gemessen werden. Ideal wäre natürlich ein Platzhalter für den jeweiligen Dienst.

Viele Grüße
dertimm

**Comment by liayn** [comment]
Falsches Repo erwischt, dieses hier ist rein da PHP backend zum share-count abfragen.
https://github.com/heiseonline/shariff/

**Comment by compeak** [comment]
Im Moment ist so ein Feature nicht geplant.
