### ISSUE TITLE
Add CA Cert bundle for SSL-connections to facebooks and co.  

### ISSUE THREAD

**Issue by jschmi01** [heiseonline/shariff-backend-php#15]
There’s a whole lot of misinformation about how to deal with the error “SSL certificate problem, verify that the CA cert is OK” from curl. Nearly everyone advises that you turn CURLOPT_SSL_VERIFYPEER off (in fact, countless comments on the PHP manual page for curl_setopt tell you this). This is bad, because it allows your nice, encrypted stream of confidential data to be silently highjacked by a bad guy (e.g. look for "man-in-the-middle-attacks").

Sharif backend uses curl - but has not yet provided / implemented needed CA Cert bundle from the curl-website. (look at: http://curl.haxx.se/docs/caextract.html). 
Implementation is quite easy:
- Download CA Cert bundle 
- add option "CURLOPT_CAINFO" (e.g. in CurlFactory.php): <code>$options[CURLOPT_CAINFO] = 'path-to-cacert-bundle/cacert.pem';</code>

**Comment by uwej711** [comment]
This should actually be a task for your servers admin, afaik curl uses the ca cert bundle installed on your system (and those can be updated e.g. on Ubuntu by running update-ca-certificates).

**Comment by jschmi01** [comment]
hi,
unless you have your own server that's OK - but if not - unfortunately there quite a lot of webhoster (as with mine), who will refuse to do so. And then you will have to modify code..

**Comment by uwej711** [comment]
Oh, maybe you should think changing your web hoster, there might be more serious issues than updating the root certificates ... anyway once PR #17 is merged, we can extend the shariff configuration to include default Guzzle config options, including timeouts (so your server will not wait indefinitely once facebook is down again) and custom ca files (see http://guzzle.readthedocs.org/en/latest/clients.html#request-options).
