### ISSUE TITLE
Request for share counts on linked in return eror 404

### ISSUE THREAD

**Issue by vkhramtsov** [heiseonline/shariff-backend-php#158]
Hi.

Last month we have response with 404 code while getting share counts for our URLs in linkedin using url  `https://www.linkedin.com/countserv/count/share?url=...`

Thank you in advance

**Comment by richard67** [comment]
Linkedin silently stopped their sharing count, see [https://developer.linkedin.com/blog/posts/2018/deprecating-the-inshare-counter](https://developer.linkedin.com/blog/posts/2018/deprecating-the-inshare-counter).

So we have to remove the LinkedIn service from Shariff Backend.

I will make a PR for that.

**Comment by richard67** [comment]
Pull request (PR) is #159 .

**Comment by vkhramtsov** [comment]
@compeak Waiting for release

**Comment by compeak** [comment]
> @compeak Waiting for release. Would you be so kind to create it?

@vkhramtsov see [8.2.0](https://github.com/heiseonline/shariff-backend-php/releases/tag/8.2.0)

**Comment by vkhramtsov** [comment]
@compeak Thank you
