### ISSUE TITLE
Only gets counts on Xing

### ISSUE THREAD

**Issue by Spider-IT** [heiseonline/shariff-backend-php#161]
I installed Shariff last month and just updated the backend to 8.2.1 (latest version).
After updating the configuration in the class Application, I only get a counter on the Xing button, which shows 0 (zero), although I shared an article there (but the url changed after that).
The other buttons won't show a counter at all.
What am I doing wrong?

Website: https://www.mud-rider.de
Configuration:
```
private static $configuration = [
        'cache' => [
            'ttl' => 60
        ],
        'domains' => [
            'www.mud-rider.de'
        ],
        'services' => [
            'Facebook',
            'Twitter',
            'WhatsApp',
            'Threema',
            'Telegram',
            'Tumblr',
            'Xing',
            'LinkedIn',
            'Reddit'
        ]
    ];
```
Server: Apache
.htaccess: RewriteRule ^shariff/.*$ - [L]
Website-Entry: &lt;div class="shariff" data-backend-url="/shariff/" data-button-style="standard" data-lang="de" data-title="&lt;title&gt;" data-services="[facebook, twitter, whatsapp, threema, telegram, tumblr, xing, linkedin, reddit, info]"&gt;&lt;/div&gt;

**Comment by compeak** [comment]
You are trying to use services that are not [supported by shariff-backend-php](https://github.com/heiseonline/shariff-backend-php#supported-services). The Facebook service needs [credentials](https://github.com/heiseonline/shariff-backend-php#facebook-service-options) to work.

**Comment by Spider-IT** [comment]
Oh, okay, thanks!
