### ISSUE TITLE
PHP-Error

### ISSUE THREAD

**Issue by startef** [heiseonline/shariff-backend-php#22]
Hallo,

ca. einmal pro Tag finde ich in meinem php-error.log folgende Einträge. Kann sich da irgendwer einen Reim drauf machen? Nicht das dies schlimm wäre, aber prinzipiell interessiert es mich doch zu verstehen, warum das auftritt.

<pre>
PHP Fatal error: Uncaught exception 'RuntimeException' with message 'SplFileInfo::getMTime(): stat failed for .../Shariff-c8/Shariff-25ad73a4dbfa7d2bf839e2cb77ab6eed.dat' in .../shariff/backend/vendor/zendframework/zend-cache/Zend/Cache/Storage/Adapter/Filesystem.php:154
Stack trace:
#0 .../shariff/backend/vendor/zendframework/zend-cache/Zend/Cache/Storage/Adapter/Filesystem.php(154): SplFileInfo->getMTime()
#1 .../shariff/backend/src/Backend.php(41): Zend\Cache\Storage\Adapter\Filesystem->clearExpired()
#2 .../shariff/backend/index.php(57): Heise\Shariff\Backend->__construct(Array)
#3.../shariff/backend/index.php(63): Application::run()
#4 {main}
thrown in .../shariff/backend/vendor/zendframework/zend-cache/Zend/Cache/Storage/Adapter/Filesystem.php on line 154
</pre>

Viele Grüße,
startef

**Comment by startef** [comment]
Mal ein kleines Update, es könnte (!) auf ein altes Problem der konkurrierenden Requests aufsetzen: Der eine versucht mit getMTime() die Zeit der letzten Änderung für die Datei zu kriegen (oder wahlweise später auch ein unlink() zu machen), während der andere diese ganz kurz vorher bereits gelöscht hat. Siehe: https://github.com/zendframework/zf2/issues/7467

Im Grunde also harmlos, weil das Ziel ja beides Mal das gleiche ist. Aber natürlich blöd, wenn trotz ExceptionHandler einem das Log voll gemüllt wird.

**Comment by wmtech-1** [comment]
This annoying but unimportant error can be solved by wrapping the foreach block into a try block. Like so:
        ErrorHandler::start();
        foreach ($glob as $entry) {
            try {
                $mtime = $entry->getMTime();
                if ($time >= $mtime + $ttl) {
                    $pathname = $entry->getPathname();
                    unlink($pathname);
                
                    $tagPathname = substr($pathname, 0, -4) . '.tag';
                    if (file_exists($tagPathname)) {
                        unlink($tagPathname);
                    }
                }
            }
            // TEMPORARY FIX: Disregard any exceptions because a race condition in ZendCache throws too many errors
            // and the ErrorHandler is not able to catch them.
            catch (\Exception $e) {}            
        }
        $error = ErrorHandler::stop();

However this should be solved in ZendFW2 and not here. But adding this helps to avoid the errors filling up in the log.

**Comment by startef** [comment]
This almost did the trick for me. I also needed to remove the $error block in order to get rid of all errors in my log permanently.
```
    if ($error) {
        $result = false;
        return $this->triggerException(
       __FUNCTION__,
        new ArrayObject(),
        $result,
        new Exception\RuntimeException('Failed to clear expired items', 0, $error)
        );
    }
```

**Comment by compeak** [comment]
I am closing this since @startef's workaround seems to be working and the underlying problem has to be fixed by Zend.
