### ISSUE TITLE
Facebook has problems with anchors and umlauts

### ISSUE THREAD

**Issue by marchert** [heiseonline/shariff-backend-php#26]
If an url has an anchor attached (e. g. "#mytarget") or contains an umlaut facebook does not work. So all anchors should be removed form an url bevor requesting the counter of facebook. And may be umlauts can be converted too. I actually replaces all umlautes in my urls manually.

Test without anchor (facebook counter is displayed):
http://www.marchert.info/brd/dokumente/datenschutzhinweise.html

Test with anchor (facebook counter is not displayed):
http://www.marchert.info/brd/dokumente/datenschutzhinweise.html#social

Edit: The umlaut problem exists with all buttons.

**Comment by liayn** [comment]
Is it safe to drop the anchors? I don't think so.
You should rather set the right url to share.

**Comment by marchert** [comment]
Why should it not be safe?

I have now added a quick and dirt solution to the facebook.php in the backend. Works for me fine.

The alternative would be to write the fix for the included sharrif div, because in a CMS you can not set data-urls manually.

**Comment by liayn** [comment]
Depends on the CMS. ;-)

**Comment by liayn** [comment]
A different anchor could mean different content. For instance if a tab-selection depends on the anchor.

**Comment by compeak** [comment]
You can use

- a canonical url
- the og:url meta tag
- the data-url attribute

as a workaround.

Please talk to the author of your third-party integration if it does not support these methods.

Sanitizing or canonicalizing URLs for specific services is not a task shariff should handle.
