### ISSUE TITLE
Shariff-Backend anpassen

### ISSUE THREAD

**Issue by susiratlos** [heiseonline/shariff-backend-php#27]
Liebes Forum,
könnt ihr mir bitte weiterhelfen?
Wie kann ich die index.php im shariff/backend mit den Pfaden anpassen, damit es passt. 
Ich denke, an dieser Stelle (Original-Datei) habe ich die Pfade falsch angelegt:

require_once __DIR__.'/vendor/autoload.php';

use Heise\Shariff\Backend;
use Zend\Config\Reader\Json;

Die Buttons werden angezeigt, aber die Counter nicht geladen.
http://eutonia.de/neu/shariff-backend-php-master/

Ich verwende PHP 5.2. - da muss ich wohl auch ein CacheDir anlegen in der shariff.json?

	"cache": {
		"ttl": 60,
		"cacheDir": "cache"
	},
	"domain": "www.eutonia.de/neu",

Danke für's Lesen und eure Hilfe. :)
Ines

**Comment by liayn** [comment]
Ohne jetzt dein Problem genau gelesen zu haben, sehe ich ein anderes Problem, nämliche deine PHP Version.

Aus der Readme:
PHP 5.4 or greater

**Comment by pmb0** [comment]
> Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /kunden/isih-web.de/hosting/3135/eutonia.de/neu/shariff-backend-php-master/index.php on line 5

Du brauchst ein neueres PHP.

**Comment by susiratlos** [comment]
Am 24.07.2015 um 11:42 schrieb Philipp Busse:
>
>     Parse error: syntax error, unexpected T_STRING, expecting
>     T_CONSTANT_ENCAPSED_STRING or '(' in
>     /kunden/isih-web.de/hosting/3135/eutonia.de/neu/shariff-backend-php-master/index.php
>     on line 5
>
> Du brauchst ein neueres PHP.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/heiseonline/shariff-backend-php/issues/27#issuecomment-124457469>.
>



Hallo Philipp,
vielen Dank für deinen Hinweis!!! :)))

Ich denke, dass es entweder an der *PHP-Version* liegt oder aber an 
meinen *Pfadangaben*!!!


*PHP*

http://www.eutonia.de/neu/

Ich habe folgende PHP-Einstellungen bei dieser domain:
http://eutonia.de/neu/shariff-backend-php-master/php_inf.php

PHP-Version:
    5-STABLE-STANDARD  5.2.17
    Die Voreinstellung für alle Domains ohne individuelle Einstellungen

Sichere Einstellungen:
    aktiviert
    Diese Option konfiguriert PHP mit einer sicheren Umgebung und
    folgenden Einstellungen:
    register_globals = off, allow_url_fopen = off, allow_url_include = off

folgende Module sind enthalten:

bcmath 		
bz2 		
calendar 		
cgi 		
ctype 		
curl 		
date 		
dba 		
dbase 		
dom 		
exif 		
filter 		
ftp 		
gd 		
gettext 		
hash 		
iconv 		
imap 		
json 		
libxml 		
mbstring 		
mcrypt 		
mhash 		
mysql 		
mysqli 		
openssl 		
pcre 		
PDO 		
pdo_mysql 		
pdo_sqlite 		
pgsql 		
posix 		
Reflection 		
session 		
SimpleXML 		
soap 		
SPL 		
SQLite 		
standard 		
tokenizer 		
wddx 		
xml 		
xmlreader 		
xmlwriter 		
xsl 		
Zend Optimizer 		
zlib



Vielleicht liegt es aber auch an meinen Pfadangaben in der ---> 
shariff-backend-php-master - idex.php

<?php
require_once __DIR__.'/vendor/autoload.php';


*use neu\shariff-backend-php-master;**
**use build\vendor\zendframework\zend-json\Zend\Json;*
class Application
{
     public static function run()
     {
         header('Content-type: application/json');

         if (!isset($_GET["url"])) {
             echo json_encode(null);
             return;
         }

         $reader = new Json();

         $shariff = new Backend($reader->fromFile('shariff.json'));
         echo json_encode($shariff->get($_GET["url"]));
     }
}
Application::run();
?>


*Meine Verzeichnisstruktur:*

/hosting/3135/eutonia.de/neu

---> /hosting/3135/eutonia.de/neu/shariff-backend-php-master (750)
---> /hosting/3135/eutonia.de/neu/shariff-master  (777)

/hosting/3135/eutonia.de/neu/shariff-backend-php-master/build/shariff.json 
(777)


Es ist schon länger her, dass ich die Verzeichnisse hergestellt habe und 
das Tool installieren wollte.
Vielleicht erkennst du einen fehler?

Vielen herzlichen Dank für deine Bemühungen, Philipp-

Herzliche Grüße aus berlin
Ines

**Comment by susiratlos** [comment]
Habe noch einmal den thread gelesen und auf PHP 5.4.16 umgestellt:

http://eutonia.de/neu/shariff-backend-php-master/php_inf.php
