### ISSUE TITLE
Facebook count not returned on live server

### ISSUE THREAD

**Issue by infovations** [heiseonline/shariff-backend-php#31]
I have tested Shariff successfully locally, and then deployed to our live website.

Locally, I get the following result for a request to the backend:
{"googleplus":20,"twitter":16,"facebook":242}

The same script on the server only returns the following:
{"googleplus":20,"twitter":16}

**Comment by infovations** [comment]
After some debugging, I can now see that Facebook seems to return the following error message:
OAuth "Facebook Platform" "invalid_request" "(#4) Application request limit reached"

For information, I am not using the Facebook authentication parameters.

**Comment by startef** [comment]
If you do not use any Facebook authentication, Facebook has a rate limit of 600 request per 600 seconds per IP address. If you are on a (cheap) shared hosting environment, many websites use the same IP address and therefore you reach that limit pretty fast.

Only solution: Create your own Facebook api credentials or upgrade to a better hosting solution.
