### ISSUE TITLE
Angabe von app_id und secret in der shariff.json

### ISSUE THREAD

**Issue by CommanderBond** [heiseonline/shariff-backend-php#36]
Hallo,

eine Frage: Wie genau lautet die Syntax der Angabe von der Facebook app_id und secret in der shariff.json?
Geht das mit folgenden Zeilen nach der Definition des "services" Array oder wie muss man das angeben?
```json
…
	"services": [
		"GooglePlus",
		"Twitter",
		"Facebook",
		"LinkedIn",
		"Reddit",
		"StumbleUpon",
		"Flattr",
		"Pinterest",
		"Xing"
	],
	"Facebook": {
		"app_id": "meineApp_id",
		"secret": "meinSecret"
	}
```

Vielen Dank!

**Comment by pmb0** [comment]
Da scheint die README nicht ganz komplett zu sein. Ja, so sollte es klappen. Klappt es?

**Comment by CommanderBond** [comment]
Das ist jetzt schwer zu sagen, denn prinzipiell werden bei Angabe wie oben Counts zurückgeliefert, ja. Wenn ich die App ID oder den Secret absichtlich verfälsche aber auch. Dann zieht scheinbar die andere Methode.

Ich habe deswegen soeben in die Facebook.php in der entsprechenden IF je ein echo eingefügt und sehe, dass bei richtiger App ID und secret in den API Zweig gesprungen wird, wenn eine der Angaben falsch ist, aber in den SELECT-Zweig.

Ich würde daher sagen, es funktioniert. Bitte um Anpassung der Readme und schließen des Issues.

**Comment by compeak** [comment]
In der [README](https://github.com/heiseonline/shariff-backend-php/blob/master/README.md) wird die Konfiguration des Facebook-Services [hier](https://github.com/heiseonline/shariff-backend-php#service-settings) erwähnt.

**Comment by CommanderBond** [comment]
@compeak Ja, ich kenne diesen Hinweis. Mir ging es nur darum, wie die Angabe genau zu erfolgen hat (Syntax).

**Comment by compeak** [comment]
[So](https://github.com/heiseonline/shariff-backend-php#full-config-example) sollte es übersichtlicher sein.

**Comment by CommanderBond** [comment]
Oh yes! Vielen Dank! Sehr hilfreich!
