### ISSUE TITLE
Keine Zähler in Drupal mit dem Drupal plugin SharuffSharingButtons

### ISSUE THREAD

**Issue by dwalin76** [heiseonline/shariff-backend-php#39]
Die Buttons werden angezeigt, aber leider ohne Zähler.

Gezählt wird aber laut https://www.familierott.de/shariff-backend/?url=https%3A%2F%2Fwww.familierott.de%2Fdrupal%2Fnode%2F60 
Hier das Ergbnis: {"googleplus":0,"twitter":0,"facebook":5,"linkedin":0,"reddit":0,"stumbleupon":0,"flattr":0,"pinterest":0,"xing":0}

Unter der Modulkonfiguration habe ich das Backend Verzeichnis mit http://www.familierott.de/shariff-backend/  angegeben.
die shariff.json sieht folgendermaßen aus:
{
        "cache": {
                "ttl": 60,
                "cacheDir": "/tmp/shariff/cache"
        },
        "domain": "www.familierott.de",
        "services": [
                "GooglePlus",
                "Twitter",
                "Facebook",
                "LinkedIn",
                "Reddit",
                "StumbleUpon",
                "Flattr",
                "Pinterest",
                "Xing"
        ]
}

Habe ich etwas übersehen?

**Comment by liayn** [comment]
https vs http?

**Comment by dwalin76** [comment]
ich habe es mit http und mit https probiert, aber beides ohne Erfolg.
I tried it with http and https, but without luck,

**Comment by liayn** [comment]
Check mal mit browser dev console welchen request er gegen den Server schickt und was da retour kommt.

**Comment by dwalin76** [comment]
Danke für den Tipp. Es lag dann doch an http und/oder https mismatch und evtl. auch zwischendurch an Änderungen die ich an der shariff.json durchgeführt habe.
 Wenn die Seite mit https aufgerufen wird und die backend URL nur mit http oder andersrum, dann klappt das nicht.

Muss wohl eine rewriterule bauen, dass entweder alles per https oder nur mit http läuft.

Danke nochmals für den Hinweis wo ich schauen muß!
