### ISSUE TITLE
Count not registering or showing when "Testing Installation"

### ISSUE THREAD

**Issue by calumbrash** [heiseonline/shariff-backend-php#40]
When I navigate to:
http://example.com/my-shariff-backend/?url=http%3A%2F%2Fwww.example.com

Only xing shows up in the array of counts. Facebook, Twitter and Linkedin (which I need) all show blank.
Attached is screenshots of sharriff.json, index.php and some others.
![screen shot 2015-08-24 at 15 25 36](https://cloud.githubusercontent.com/assets/12020857/9441127/6ffc42ba-4a74-11e5-86eb-2f5e820dd679.png)
![screen shot 2015-08-24 at 15 26 43](https://cloud.githubusercontent.com/assets/12020857/9441147/9646b64e-4a74-11e5-92d1-91513e91ddd0.png)

![screen shot 2015-08-24 at 15 25 04](https://cloud.githubusercontent.com/assets/12020857/9441128/6ffd711c-4a74-11e5-8a18-ed5da37a75f3.png)
![screen shot 2015-08-24 at 15 24 55](https://cloud.githubusercontent.com/assets/12020857/9441129/70004ef0-4a74-11e5-8f2f-b15b12425abe.png)

**Comment by liayn** [comment]
The url you called in the second-last screenshot does not match the HTML code you posted in the image before. Please verify the exact call to the backend via browser network tools.

Furthermore I'm not sure about the `./a/` backend url. Why not using either an absolute or a real relative path?

What does the PHP error log say and the webserver's log?
