### ISSUE TITLE
PHP7 Compatibility?

### ISSUE THREAD

**Issue by wmtech-1** [heiseonline/shariff-backend-php#44]
There are a lot of potential issues with PHP 7 (which will be released very soon). Can we expect to have those checked (and if necessary corrected) soon?

Thanks!

#### /vendor/guzzlehttp/guzzle/src/Message/AbstractMessage.php
* foreachByReference
 * Line 78: `            foreach ($value as &$v) {`

#### /vendor/guzzlehttp/guzzle/src/UriTemplate.php
* foreachByReference
 * Line 152: `                        foreach ($kvp as $k => &$v) {`

#### /vendor/guzzlehttp/guzzle/tests/Message/FutureResponseTest.php
* funcGetArg
 * Line 120: `            $err = func_get_args()[1];`

#### /vendor/guzzlehttp/guzzle/tests/Message/MessageParserTest.php
* foreachByReference
 * Line 241: `        foreach ($normalized as $key => &$value) {`

#### /vendor/guzzlehttp/guzzle/tests/perf.php
* yield
 * Line 33: `        yield $client->createRequest('GET', '/guzzle-server/perf');`

#### /vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php
* funcGetArg
 * Line 429: `                        $args = func_get_args();`

#### /vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
* funcGetArg
 * Line 304: `            $passed = func_get_args();`

#### /vendor/guzzlehttp/ringphp/src/Core.php
* funcGetArg
 * Line 22: `            $args = func_get_args();`

#### /vendor/guzzlehttp/ringphp/tests/Client/CurlFactoryTest.php
* funcGetArg
 * Line 298: `                    $called[] = func_get_args();`

#### /vendor/guzzlehttp/ringphp/tests/Client/Server.php
* foreachByReference
 * Line 75: `        foreach ($result as &$res) {`

#### /vendor/guzzlehttp/ringphp/tests/Client/StreamHandlerTest.php
* funcGetArg
 * Line 319: `                $called[] = func_get_args();`
 * Line 334: `                $called[] = func_get_args();`

#### /vendor/guzzlehttp/ringphp/tests/CoreTest.php
* funcGetArg
 * Line 192: `            $called['a'] = func_get_args();`
 * Line 195: `            $called['b'] = func_get_args();`

#### /vendor/guzzlehttp/streams/src/Utils.php
* funcGetArg
 * Line 30: `                func_get_args()[1]`

#### /vendor/react/promise/tests/PromiseAdapter/CallbackPromiseAdapter.php
* funcGetArg
 * Line 13: `        return call_user_func_array($this->callbacks['promise'], func_get_args());`
 * Line 17: `        return call_user_func_array($this->callbacks['resolve'], func_get_args());`
 * Line 21: `        return call_user_func_array($this->callbacks['reject'], func_get_args());`
 * Line 25: `        return call_user_func_array($this->callbacks['notify'], func_get_args());`
 * Line 29: `        return call_user_func_array($this->callbacks['settle'], func_get_args());`

#### /vendor/zendframework/zend-cache/src/Pattern/ObjectCache.php
* funcGetArg
 * Line 251: `        return $this->call('__invoke', func_get_args());`

#### /vendor/zendframework/zend-cache/src/Storage/Adapter/Apc.php
* foreachByReference
 * Line 378: `        foreach ($normalizedKeyValuePairs as $normalizedKey => &$value) {`

#### /vendor/zendframework/zend-cache/src/Storage/Capabilities.php
* foreachByReference
 * Line 202: `        foreach ($datatypes as $type => &$toType) {`

#### /vendor/zendframework/zend-cache/src/Storage/Plugin/Serializer.php
* foreachByReference
 * Line 72: `        foreach ($result as &$value) {`

#### /vendor/zendframework/zend-json/src/Server/Server.php
* funcGetArg
 * Line 73: `            $argv = func_get_args();`
 * Line 111: `            $argv = func_get_args();`

#### /vendor/zendframework/zend-stdlib/src/ArrayUtils.php
* foreachByReference
 * Line 175: `                foreach ($haystack as &$h) {`

#### /vendor/zendframework/zend-stdlib/src/CallbackHandler.php
* funcGetArg
 * Line 130: `        return $this->call(func_get_args());`

**Comment by liayn** [comment]
This are all third party issues. There are newer versions of guzzle available, which should be PHP 7 compatible if I'm not mistaken. I've no clue about ZF though.

**Comment by compeak** [comment]
Pull requests upgrading guzzle are welcome. I would love tests with mock handlers instead of real API endpoints, too.

**Comment by liayn** [comment]
As a first step, I fixed a lot of dependency issues see: https://github.com/heiseonline/shariff-backend-php/pull/55
After that I streamlined the test setup: https://github.com/heiseonline/shariff-backend-php/pull/57

The next step is to upgrade guzzle. This will include the major breaking change that the minimum PHP version is then 5.5.

**Comment by compeak** [comment]
[It looks like PHP 7 has been released.](https://github.com/php/php-src/releases/tag/php-7.0.0)

**Comment by compeak** [comment]
[Travis now has a PHP 7 test environment.](https://docs.travis-ci.com/user/languages/php)
