### ISSUE TITLE
Skype announces Share buttom

### ISSUE THREAD

**Issue by CommanderBond** [heiseonline/shariff-backend-php#45]
Since Skype announced a share button today, would it be possible to integrate it into Shariff?
http://blogs.skype.com/2015/11/04/introducing-share-button-effortless-sharing-that-sparks-richer-conversations/

**Comment by liayn** [comment]
Does Skype provide an API to query the number of shares?
This should first place to https://github.com/heiseonline/shariff as this repo is only about the backend.

**Comment by compeak** [comment]
Please reopen once Shariff provides a Skype button.
