### ISSUE TITLE
Getting rid of Zend Json

### ISSUE THREAD

**Issue by liayn** [heiseonline/shariff-backend-php#56]
Would you agree to remove the usage of `Zend\Config\Reader\Json` in the demo index.php?

**Comment by compeak** [comment]
Please suggest how to do this.

**Comment by core23** [comment]
I think we can remove `zend-json` form the composer config, because only the `index.php` test file uses this. This is not part of any source or tests.

**Comment by core23** [comment]
`zend-json` isn't used anywhere. We use `zend-config` in the `index.php` file. We can remove this dependency too.

**Comment by liayn** [comment]
I would simply inline the JSON into the `index.php` file.
There is absolutely no need to have this in a dedicated file and most integrations will feed the config from something else anyway. (e.g. TYPO3 content elements)

**Comment by compeak** [comment]
> I would simply inline the JSON into the index.php file.

Maybe index.php should include some kind of config.php containing the configuration as a PHP data structure.

This change requires updates to README.md.

A pull request would be very welcome.
