### ISSUE TITLE
usability

### ISSUE THREAD

**Issue by craiq** [heiseonline/shariff-backend-php#59]
Now you cut out user, that have problems installing composer. 
For this you need an installed php, what is pain in the ass itself.
So you should bring back the build folder or add the vendor --no-dev to the repo.
Then you still have tons of unused stuff.

**Comment by liayn** [comment]
I'm not sure if I understood your concern correctly.
If you don't wanna develop with the code, you can simply download the builds now.
https://github.com/heiseonline/shariff-backend-php/releases

**Comment by craiq** [comment]
ahhh ok didn't realize this.
In the readme the build folder is still mentioned
