### ISSUE TITLE
Keine Zähler

### ISSUE THREAD

**Issue by skyynet** [heiseonline/shariff-backend-php#6]
Nach einigen Stunden Suche weiß ich leider keine andere Möglichkeit mehr, als hier zu fragen.
Ich habe statt der Social Media Buttons nun Shariff bei mir installiert. Funktioniert auch, aber ich bekomme keine Zähler.

Testseite unter www.skyynet.de/_test.htm

Auf meinem Server läuft PHP 5.5, Das Backend liegt unter www.skyynet.de/shariff
Die json habe ich konfiguriert unter www.skyynet.de/shariff/shariff.json

Auf der Seite habe ich die Buttons eingebunden über <div class="shariff" data-services="[&quot;facebook&quot;,&quot;twitter&quot;,&quot;googleplus&quot;]" data-backend-url="/shariff/" data-orientation="vertical"></div>

Wenn ich den testweise http://www.skyynet.de/shariff/?url=http%3A%2F%2Fwww.skyynet.de aufrufe, erhalte ich nur [].

**Comment by skyynet** [comment]
Da ich meines Wissens alle Voraussetzungen auf meinem PHP Server erfülle, verstehe ich nicht, warum es nicht klappt. Hat noch jemand eine Idee? Ohne Zähler, sieht Shariff irgendwie nackt aus :-(

**Comment by jschmi01** [comment]
hi,
Problem wird durch das php-curl interface in Zusammen hang mit ssl/tls verursacht. Eine Lösung (quick aber u. U. dirty/unsicher) ist, die option "CURLOPT_SSL_VERIFYPEER" in dem file CurlFactory.php auf "false" zu setzen.

**Comment by skyynet** [comment]
Hi jschmi01,
DANKE!!!!!!!!!!
Das hat es gelöst. Im PHP Log war nix und ich war echt am Ende mit meinem (nicht vorhandenem) Latein. Wie kommt es, dass der Fehler auch ohne SSL auftritt? Meine Website kann ja mit und ohne SSL genutzt werden.

**Comment by jschmi01** [comment]
hi,
die URLs von Facebook und Co. sind HTTPS (SSL) Verbindungen. Die Implementierung des Backends für die HTTPS-Verbindungen ist mit der CURL-Api gebaut. Dabei ist standardmäßig für das SSL-Handshake Protokoll sowohl Client- als auch Server-idenfikation via CA-Certificates eingestellt (CURLOPT_SSL_VERIFYPEER = true). Dafür brauchen dann Client als auch Server **bekannte** CA-Certificates. Dies ist aber in deinem (wie auch bei meinem Server/Provider) nicht der Fall - die Kommunikation zu Facebook und Co. wird dann mit dem Fehler "unbekanntes Zertifikat" abgebrochen und somit können keine Zähler abgeholt werden.

**Comment by skyynet** [comment]
Danke für die Info. Ich habe ein Wildcard SSL Zertifikat eines von allen Browsern akzeptierten CA. Vielleicht hat Curl aber Probleme mit Wildcard. Da ich keine PHP Errordatei bekam, wußte ich nicht, woran es liegt. Jetzt schon.
