### ISSUE TITLE
Mehr als eine Domain nutzen können

### ISSUE THREAD

**Issue by frankthies** [heiseonline/shariff-backend-php#61]
Hallo,

shariff ist wirklich ein sehr gutes Tool und ich würde es gern in einem Projekt nutzen, in welchem über ein (eigenentwickeltes) CMS verschiedene Websites mit unterschiedlichen Domains verwaltet werden. Bisher habe ich keine Möglichkeit gefunden, wie man in der shariff.json mehrere Domains angeben kann. Für jede einzelne Domain ein separates shariff-backends einzurichten, treibt den Aufwand bei Updates aber sehr nach oben.

Gibt es denn die Möglichkeit mehere Domains mit einer shariff-backend-Installation zu nutzen resp. wenn nicht, könnte das nicht in das Script mit eingearbeitet werden?

Danke im Voraus / VG

Frank-André Thies

**Comment by liayn** [comment]
Hallo!

Du musst ja die config nicht aus einer json lesen, sondern kannst die Config ja direkt generieren und an die Backend-Klasse weitergeben.
Dann kannst du deine Domain nach Belieben festlegen bzw. dynamisieren.

**Comment by frankthies** [comment]
OK, sorry, dass war mir bisher nicht bewußt. Habe mir die readme noch mal angeschaut und gesehen, dass man per use Heise\Shariff\Backend; das backend direkt aufrufen kann. Aber wie bekomme ich dann die Counterwerte in die Buttons übertragen? Das habe ich leider noch nicht verstanden.

Danke!

**Comment by liayn** [comment]
```
$theUrl = 'http://example.com';
$config = [
    'domain' => 'example.com',
    'facebook...' => '...',
    ...
];
$shariff = new Backend($config);
$theResults = $shariff->get($theUrl);
// $theResults now holds an array of couter values, which you can pass along wherever you like
// most likely you will json_encode() them and return them as result of the AJAX query back to the shariff frontend
```

**Comment by frankthies** [comment]
Hallo liayn,

Danke für Deine Hilfe und sorry wenn ich nerven sollte. Ich habe das alles bis zum Abruf der Daten verstanden und das ich json_encode anzuwenden habe, bevor die Daten verarbeitet werden können. Aber den Teil ab dann verstehe ich nicht. Ich habe doch keine "Feld" in der shariff-DIV, wo ich die Daten eintragen kann:

<div class="shariff" data-services="[&quot;facebook&quot;,&quot;googleplus&quot;,&quot;xing&quot;,&quot;stumbleupon&quot;,&quot;twitter&quot;,&quot;whatsapp&quot;]" data-url="http://www.xxx.de"></div>

Also kann ich die Daten nicht so "eintragen", sondern muss ein separates Script schreiben, dass ich in der data-backend-url="" eintrage. Sehe ich das richtig so?

Danke

Frank

**Comment by liayn** [comment]
Ich bin mir nicht sicher was du genau meinst.

Der Ablauf funktioniert grundsätzlich so:
* Das Shariff JS baut die ganzen sharing buttons
* Wenn das div-tag eine `data-backend-url` hat, dann schickt es eine AJAX-Anfrage an diese Adresse, wo als Parameter die aktuelle URL, wo die buttons sind (oder die URL, die im `data-url` attribute steht), übergeben wird.
* Das Script unter der `data-backend-url` ist ein Script von dir (oder deinem CMS), das eine AJAX Anfrage entgegennehmen kann. Du verwendest darin das Shariff-Backend.
* Das Shariff-Backend prüft, ob die übergebene URL "zulässig" ist, indem es gegen die konfigurierten Domains (`domain`) vergleicht. Wenn keine Domains angegeben sind, dann sind alle URLs zulässig.
* Das Backend fragt dann bei den diversen Portalen die Zahlen ab und gibt die dann als PHP array an dein Script retour. Du musst dann das Resultat im JSON-Format als Antwort rausschicken.
* Das Shariff JS im Browser nimmt die Antwort vom AJAX-Script, also das JSON, entgegen und bastelt die Nummern bei den buttons dazu.

**Comment by frankthies** [comment]
Sorry, Du hast Recht, ich habe mich schlecht ausgedrückt. Danke für die ausführliche Antwort, habe es nun (hoffentlich *grins*) endgültig verstanden.

Ich meinte, dass ich das backend-Script (index.php) so anpassen muss, damit es die Grunddaten nicht aus der shariff.json ausließt sondern per PHP übergebe oder aus einer Datenbank auslese. Wenn man aber einfach die Variable domain weglassen kann, dann kann man natürlich u.U. darauf verzichten. Erhöht "nur" das Risiko einer mißbräuchlichen Nutzung des Scripts und das will ich natürlich auch nicht zulassen :)

Danke nochmal für Deine Hilfe!!!

**Comment by compeak** [comment]
Ich schliesse das Ticket mal. Oeffnet es einfach wieder, falls es neue Fragen gibt.
