### ISSUE TITLE
New release / tag

### ISSUE THREAD

**Issue by core23** [heiseonline/shariff-backend-php#62]
Could you please create a new release or branch alias (4.0.x-dev) to get rid of old zend dependencies.

**Comment by compeak** [comment]
I will release v4.0 soon. Support for PHP 7 will be a v5.0 thing.

**Comment by compeak** [comment]
[Done.](https://github.com/heiseonline/shariff-backend-php/releases/tag/4.0.0)

**Comment by core23** [comment]
Thank you :)
