### ISSUE TITLE
Zend Config Reader Json not found

### ISSUE THREAD

**Issue by hokascha** [heiseonline/shariff-backend-php#63]
Fresh install gives  
```
Class 'Zend\\Config\\Reader\\Json' not found in /htdocs/shariff-backend/index.php on line 19
```

**Comment by compeak** [comment]
I should have done more testing. [4.0.1](https://github.com/heiseonline/shariff-backend-php/releases/tag/4.0.1) re-adds the necessary dependencies and makes the backend work again.
