### ISSUE TITLE
cache directory not cleaned

### ISSUE THREAD

**Issue by jschmi01** [heiseonline/shariff-backend-php#7]
seems that design of php-backend has no functionality to clean obsolete/expired cache-entries in cache-directory. Can somebody clarify this issue?

**Comment by devimplode** [comment]
I'd recommend a cron script to cleanup your cache directory.

**Comment by jschmi01** [comment]
hi,
cron has no knowledge about expired cache entries - zend framework should take care for this issue:
I've added code to Backend.php ( funktion "get($url)" ):

     $this->cache->clearExpired();

prior to getting cached items.

**Comment by devimplode** [comment]
Well, this looks quite nice.
To be honest I've never used zend or Guzzle before.
Would you mind to create pull request?

PS: Performance could be optimized if it's called after the request is handled (send with correct content-length header). So it wouldn't block the client.

**Comment by jschmi01** [comment]
hi,
you are correct - call should be done after client got contents -
Pull request:  no problem go ahead
