### ISSUE TITLE
Client defaults use wrong array index

### ISSUE THREAD

**Issue by ricktap** [heiseonline/shariff-backend-php#83]
In /src/Backend.php:33 the line 

`$client = new Client(['defaults' => $clientOptions]);`

 uses the defaults keys. I think this should actually be:

`$client = new Client($clientOptions);`

as described in http://docs.guzzlephp.org/en/latest/request-options.html

I tested it by setting the "client": { "verify": false }, it didn't work before, but works now. But maybe I'm missing something :)

**Comment by liayn** [comment]
Looks very valid. I think we overlooked that while doing the guzzle 5->6 migration.

**Comment by compeak** [comment]
Fixed in f2d6dab.
