### ISSUE TITLE
Verständnisproblem

### ISSUE THREAD

**Issue by derSteffen** [heiseonline/shariff-backend-php#84]
Hallo werte Gemeinde,

ich habe ein paar Verständnisprobleme und hoffe auf eure Hilfe!

Zum Testen des Backends!
1) Muss dazu auf meiner Webseite der Frontend-Code 
`<span class="shariff" data-theme="grey" data-lang="de" data-services="[&quot;facebook&quot;]" data-backend-url="/my-shariff-backend/" ></span>` vorhanden sein, wenn ich erstmal nur testen will ob http://meine-Domain.de/my-shariff-backend/ überhaupt funktioniert?

2) Muss zum Testen in der JSON meine Webadresse drin stehen oder kann ich auch eine andere Webseite von mir angeben, welche bereits Facebook-Fans hat, bzw. geteilte Inhalt ... oder z.B. heise.de

3) Ich habe kein PHP5.5 und habe somit in meinem Ordner  "my-shariff-backend" eine htaccess anegelegt und diese mit Hilfe von "AddHandler php56-cgi .php" manipuliert .. hat da jemand Erfahrungen ob das Einschränkungen mit sich führt?

4) 
a) Muss ich eine "Blanko"Facebook-App erstellen um an AppID und Secret ran zu kommen?
b) Muss diese App Online sein oder reicht es wenn ich die AppID und das Secret habe und eingebe
c) kann ich mit diese "Blanko"Facebook-App den Service dieses Scriptes auf mehreren Domains nutzen

5) Muss ich alles hochladen was sich im Zip befindet, also auch die Ordner **src **und  **vendor**?

Nun zu mein Problem:
Bei mir wird nur **null** angezeigt wenn ich http://meine-DOMAIN.de/my-shariff-backend/ aufrufe! Ist das normal oder muss da z.B: was anderes stehen?

Wenn ich folgendes Aufrufe:
http://meine-DOMAIN.de/my-shariff-backend/?url=http//meine-DOMAIN.de kommt auch nur **null**

Übrigens habe ich sogar schon alle Dateien und Ordern auf 777 gesetzt, trotzdem wird nichts in mein tmp reingeschrieben!

Muss ich den tmp-Order erstellen? Habe ich auch schon gemacht, direkt in den Ordner "my-shariff-backend" aber leider auch nichts!

Muss ich denn bei Adapter auch was eintragen?

So sieht meine JSON aus:

```javascript
{
	"cache": {
		"ttl": 60,
		"cacheDir": "tmp/"
	},
	"domains": [
		"www.heise.de",
		"www.ct.de"
	],
	"services": [
		"GooglePlus",
		"Facebook",
		"LinkedIn",
		"Reddit",
		"StumbleUpon",
		"Flattr",
		"Pinterest",
		"Xing",
		"AddThis"
	]
}
```

Es würde mich freune, wenn man mir helfen könnte. ich habe schon etliches ausprobiert!

Vielen Dank

**Comment by liayn** [comment]
1.) nein
2.) nein, jede beliebige Adresse geht, sofern die Konfiguration des backends auch alle domains zulässt (siehe option `domains`)
3.) Problem nicht ganz verstanden. Ist ein PHP >= 5.5 nun vorhanden oder nicht am Server? Ansonsten sollte ein `AddHandler` grundsätzlich gehen.
4.) a) ja b) weiß ich nicht c) ja
5.) ja alles, sonst wirds nicht funktionieren

Dein "Problem": Lies bitte das README aufmerksam durch und schau dir vor allem eine `domains` config nochmal im Detail an. Da sollten wohl eher deine Domains stehen, sonst wird dir das Script schlichtweg nichts ausspucken.

Das `cacheDir` muss ein Verzeichnis relativ zu Lage der `index.php` sein und PHP muss Schreibzugriff haben.

**Comment by compeak** [comment]
Ich schließe das Ticket wegen Inaktivität. Bei Bedarf bitte wieder öffnen.
