### ISSUE TITLE
Google+ showing 0 shares

### ISSUE THREAD

**Issue by immist** [heiseonline/shariff-backend-php#88]
In the latest release of shariff-backend-php (5.2.0) , the Google+ share count is broken (sending invalid requests to the Google API), due to the upgrade to Guzzle 6. 

The easiest fix would be to continue using Guzzle 5.

**Comment by liayn** [comment]
Seems related to this comment here: https://github.com/heiseonline/shariff-backend-php/commit/d4662a579f36b2d8fedaebf332b6049e9d3d98db#commitcomment-16702316

**Comment by liayn** [comment]
This is fixed with patch for #89
